import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="bg-gradient-to-r from-[rgb(194,238,112)] to-[rgb(60,223,156)]">
        {children}
      </body>
    </html>
  );
}
//bg-gradient-to-r from-[rgb(203,237,129)] to-[rgb(60,222,155)

// <body className="bg-[rgb(194,238,112)]">{children}</body>
